### ISSUE TITLE
Missing thenAnswerWith for When<FutureOr<T>>

### ISSUE THREAD

**Issue by kmcgill88** [shinayser/mocktailx#2]
Awesome extensions! I use riverpod and have a lot of `FutureOr<T>` responses. I noticed this is missing `thenAnswerWith` for that scenario. Would you be open to a PR to add

```dart
extension GenericAnswer<T> on When<FutureOr<T>> {
  /// The function will be called and completed with [value].
  void thenAnswerWith(T value) => thenAnswer((_) => Future<T>.value(value));
}
```

Very subtle difference, `When<FutureOr<T>>` vs `When<Future<T>>`.

Thanks!

**Comment by shinayser** [comment]
Hey man, thanks for the issue! 
May I ask you for a PR? Would be very helpful since I am very busy at the moment.

Thanks 👍👍👍

**Comment by kmcgill88** [comment]
Resovled by https://github.com/shinayser/mocktailx/pull/3
